require: rubocop-rspec

# Styles

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false


# Layout

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

#RSpec

RSpec/DescribedClass:
  EnforcedStyle: explicit
